modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Particle-Mimicry/issues"
license="MIT"

[[mods]]
modId="particlemimicry"
version="${file.jarVersion}"
displayName="Particle Mimicry"
displayURL="https://www.curseforge.com/minecraft/mc-mods/particle-mimicry"
authors="Mrbysco, ShyNieke"
credits="ShyNieke for the idea"
description='''
Adds a block that can generate particles
'''

[[dependencies.particlemimicry]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.particlemimicry]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="particlemimicry.mixins.json"